language: python
services: mongodb

python:
  - 2.7

cache:
  directories:
    - $HOME/.pip-cache

install: 
  - sudo add-apt-repository ppa:andrewrk/libgroove --yes
  - sudo apt-get update
  - sudo apt-get install ffmpeg libpng3 libgroove4
  - cd hummedia/utils/waveform-2.0.0 && make
  - pip install -r requirements.txt --no-use-wheel --download-cache $HOME/.pip-cache

before_script: cp hummedia/config.template.py hummedia/config.py
  
script: py.test hummedia/test -l
